# Site settings
title: 南京 Linux 用户组
email: 
description: 建一个友好的 Linux 本地社区
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nanjinglug.org" # the base hostname & protocol for your site
twitter_username: nanjinglug
github_username:  njlug

# Build settings
markdown: kramdown
